services:
  autoware:
    image: ghcr.io/oguzkaganozt/autoware-tools:autoware-amd64
    volumes:
      - autoware_map:/root/autoware_map
    environment:
      # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - RUN_MODE=planning-simulator
      - SCENARIO_SIMULATION=true
  
  scenario_simulator:
    image: ghcr.io/oguzkaganozt/autoware-tools:scenario-simulator-amd64
    volumes:
      - autoware_map:/opt/autoware/share/kashiwanoha_map/map  
    # environment:
    #   - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  visualizer:
    image: ghcr.io/oguzkaganozt/autoware-tools:visualizer-amd64
    # environment:
    #   - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 6080:6080

volumes:
  autoware_map:
