services:
  autoware:
    image: ghcr.io/autowarefoundation/autoware:universe
    depends_on:
      - visualizer
    network_mode: service:visualizer
    env_file:
      - .env
    volumes:
      - $HOME/autoware_map/sample-map-planning:/root/autoware_map
      - xauthority_vol:/root/.Xauthority:ro
    command: >
      ros2 launch autoware_launch planning_simulator.launch.xml
      map_path:=/root/autoware_map
      vehicle_model:=sample_vehicle
      sensor_model:=sample_sensor_kit

  visualizer:
    image: ghcr.io/autowarefoundation/autoware-tools:visualizer
    env_file:
      - .env
    volumes:
      - xauthority_vol:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 6080:6080

volumes:
  xauthority_vol: {}
