name: docker-build-and-push

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  docker-build-and-push-tools:
    needs: [load-env]
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-22.04
            arch-platform: linux/amd64
            lib-dir: x86_64
          - platform: arm64
            runner: ubuntu-22.04-arm
            arch-platform: linux/arm64
            lib-dir: aarch64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@v45
        with:
          files: |
            *.env
            *.repos
            .github/actions/combine-multi-arch-images/action.yaml
            .github/actions/docker-build-and-push*/action.yaml
            .github/workflows/docker-build-and-push.yaml
            ansible-galaxy-requirements.yaml
            ansible/**
            docker/**

      - name: Free disk space
        if: ${{ steps.changed-files.outputs.any_changed == 'true' ||
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'push' && github.ref_type == 'tag') }}
        uses: ./.github/actions/free-disk-space

      - name: Build 'autoware-tools'
        if: ${{ steps.changed-files.outputs.any_changed == 'true' ||
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'push' && github.ref_type == 'tag') }}
        uses: ./.github/actions/docker-build-and-push-tools
        with:
          platform: ${{ matrix.platform }}
          target-image: autoware-tools
          build-args: |
            *.platform=${{ matrix.arch-platform }}
            *.args.ROS_DISTRO=${{ needs.load-env.outputs.rosdistro }}
            *.args.LIB_DIR=${{ matrix.lib-dir }}

      - name: Show disk space
        if: always()
        run: |
          df -h

  update-docker-manifest-tools:
    needs: docker-build-and-push-tools
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Combine multi arch images for 'autoware-tools'
        uses: ./.github/actions/combine-multi-arch-images
        with:
          package-name: autoware-tools
